name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: c5f27b9534bd12287e0bbe0a00d21b5d96e62691

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:

  kcoinchprod:
    orderers:

      - orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e-0.orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.default.svc.cluster.local

    peers:

      peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      # - kcoinprod:1.0.0
      - ${fabricChainCodeId}

organizations:

  c5f27b9534bd12287e0bbe0a00d21b5d96e62691:
    mspid: c5f27b9534bd12287e0bbe0a00d21b5d96e62691MSP

    cryptoPath:  ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/msp
    tlsCryptoKeyPath: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/tls/server.key
    tlsCryptoCertPath: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/tls/server.crt

    peers:

      - peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local

      - peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local

    certificateAuthorities:
      - ca-org1

    signedCert:
      path: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/msp/signcerts/User1@c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local-cert.pem

    adminPrivateKey:
      path: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/msp/keystore/${adminPrivateKeyFile}

  ordererorg:
      mspID: "2fbb657e4c127d6f42c0989d1c3b1168c8683f3eMSP"

      cryptoPath: ${fabricCertificatesPath}/2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.orderer/msp
# orderer-eip: 49.4.7.166
orderers:

  orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e-0.orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.default.svc.cluster.local:
    url: grpcs://orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e-0.orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.default.svc.cluster.local:30805

    grpcOptions:
      ssl-target-name-override: orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e-0.orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.default.svc.cluster.local
      grpc-max-send-message-length: 15
      sslProvider: openSSL
      negotiationType: TLS
      hostnameOverride: orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e-0.orderer-2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.default.svc.cluster.local

    tlsCACerts:
      path: ${fabricCertificatesPath}/2fbb657e4c127d6f42c0989d1c3b1168c8683f3e.orderer/msp/tlscacerts/tlsca.2fbb657e4c127d6f42c0989d1c3b1168c8683f3e-cert.pem

peers:


  peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:


    url: grpcs://peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:30605
    eventUrl: grpcs://peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:30705

    grpcOptions:
      ssl-target-name-override: peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      negotiationType: TLS
      clientKeyFile: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/tls/server.key
      clientCertFile: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/tls/server.crt
      hostnameOverride: peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-0.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local


    tlsCACerts:
      path: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/msp/tlscacerts/tlsca.c5f27b9534bd12287e0bbe0a00d21b5d96e62691-cert.pem


  peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:


    url: grpcs://peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:30606
    eventUrl: grpcs://peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local:30706

    grpcOptions:
      ssl-target-name-override: peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      negotiationType: TLS
      clientKeyFile: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/tls/server.key
      clientCertFile: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/tls/server.crt
      hostnameOverride: peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691-1.peer-c5f27b9534bd12287e0bbe0a00d21b5d96e62691.default.svc.cluster.local


    tlsCACerts:
      path: ${fabricCertificatesPath}/c5f27b9534bd12287e0bbe0a00d21b5d96e62691.peer/msp/tlscacerts/tlsca.c5f27b9534bd12287e0bbe0a00d21b5d96e62691-cert.pem

certificateAuthorities:
  ca-org1:
    url: https://ca_peerOrg1:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
      client:
       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca-org1